services:
  db:
    image: postgres:17.6-alpine
    container_name: postgresql-news-app
    restart: always
    environment:
      - POSTGRES_USER=ngtuonghy
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_db
    ports:
      - '6543:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    image: redis:8.2.1-alpine
    container_name: redis-news-app
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data
  s3:
    image: minio/minio
    container_name: minio-news-app
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Console Port
    volumes:
      - minio_volume:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" 
    env_file:
      - path: .env
        required: false
      - path: .env.dev
        required: false 
  # app:
  #   build: ./app
  #   container_name: news-app
  #   ports:
  #     - "4321:4321"
  #   environment:
  #     DB_USER: ngtuonghy
  #     DB_PASSWORD: postgres
  #     DB_NAME: news_db
  #     DB_HOST: db    
  #     DB_PORT: 5432
  #     REDIS_HOST: redis   
  #     REDIS_PORT: 6379
  #     NODE_ENV: production
  #     MINIO_PORT: 9000
  #     MINIO_CONSOLE_PORT: 9001
  #     MINIO_ACCESS_KEY: ngtuonghy
  #     MINIO_SECRET_KEY: ngtuonghy1234
  #     MINIO_BUCKET: mybucket
  #     MINIO_ENDPOINT: minio
  #   depends_on:
  #     - db
  #     - redis
  #     - s3
volumes:
  db:
  redis_volume:
  minio_volume:

